ARG BASE_IMAGE=scratch
FROM ${BASE_IMAGE}

USER root
WORKDIR /opt/taskhub
COPY pyproject.toml README.md ./
COPY src ./src
RUN python -m pip install --no-deps --no-build-isolation --force-reinstall . \
    && chown -R taskhub:taskhub /opt/taskhub

ARG TASKHUB_VERSION=0.1.0-alpha
ARG TASKHUB_COMMIT=unknown
ARG IMAGE_TITLE=TaskHub
LABEL org.opencontainers.image.title="${IMAGE_TITLE}" \
      org.opencontainers.image.version="${TASKHUB_VERSION}" \
      org.opencontainers.image.revision="${TASKHUB_COMMIT}"

USER taskhub
